//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserService")]
public interface IUserService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SaveUserCharacteristic", ReplyAction="http://tempuri.org/IUserService/SaveUserCharacteristicResponse")]
    bool SaveUserCharacteristic(long userId, string key, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SaveUserCharacteristic", ReplyAction="http://tempuri.org/IUserService/SaveUserCharacteristicResponse")]
    System.Threading.Tasks.Task<bool> SaveUserCharacteristicAsync(long userId, string key, string value);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserServiceChannel : IUserService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserServiceClient : System.ServiceModel.ClientBase<IUserService>, IUserService
{
    
    public UserServiceClient()
    {
    }
    
    public UserServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool SaveUserCharacteristic(long userId, string key, string value)
    {
        return base.Channel.SaveUserCharacteristic(userId, key, value);
    }
    
    public System.Threading.Tasks.Task<bool> SaveUserCharacteristicAsync(long userId, string key, string value)
    {
        return base.Channel.SaveUserCharacteristicAsync(userId, key, value);
    }
}
