//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Services.WcfClient
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IUserExtension")]
    public interface IUserExtension
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserExtension/GetCharacteristicValue", ReplyAction = "http://tempuri.org/IUserExtension/GetCharacteristicValueResponse")]
        string GetCharacteristicValue(long userId, string key);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserExtension/GetCharacteristicValue", ReplyAction = "http://tempuri.org/IUserExtension/GetCharacteristicValueResponse")]
        System.Threading.Tasks.Task<string> GetCharacteristicValueAsync(long userId, string key);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserExtensionChannel : IUserExtension, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserExtensionClient : System.ServiceModel.ClientBase<IUserExtension>, IUserExtension
    {

        public UserExtensionClient()
        {
        }

        public UserExtensionClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public UserExtensionClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserExtensionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserExtensionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string GetCharacteristicValue(long userId, string key)
        {
            return base.Channel.GetCharacteristicValue(userId, key);
        }

        public System.Threading.Tasks.Task<string> GetCharacteristicValueAsync(long userId, string key)
        {
            return base.Channel.GetCharacteristicValueAsync(userId, key);
        }
    }
}
