//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using eCommerce.Services.WcfClient.Entities;
namespace eCommerce.Services.WcfClient.Entities
{
    using System.Runtime.Serialization;
    using eCommerce.Services.WcfClient.Users;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCharacteristic", Namespace="http://schemas.datacontract.org/2004/07/eCommerce.Data.Domain.Users.Entities")]
    public partial class UserCharacteristic : eCommerce.Core.EntityBase
    {
        
        private string KeyField;
        
        private User UserField;
        
        private long UserIdField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/eCommerce.Data.Domain.Users.Entities")]
    public partial class User : eCommerce.Core.EntityBase
    {
        
        private string EmailField;
        
        private PasswordKit PasswordKitField;
        
        private System.Guid UserGuidField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PasswordKit PasswordKit
        {
            get
            {
                return this.PasswordKitField;
            }
            set
            {
                this.PasswordKitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}
//namespace eCommerce.Services.WcfClient.Core
//{
//    using System.Runtime.Serialization;
//    using eCommerce.Services.WcfClient.Entities;
    
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/eCommerce.Core")]
//    [System.Runtime.Serialization.KnownTypeAttribute(typeof(User))]
//    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UserCharacteristic))]
//    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject
//    {
        
//        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
//        private int IdField;
        
//        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
//        {
//            get
//            {
//                return this.extensionDataField;
//            }
//            set
//            {
//                this.extensionDataField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public int Id
//        {
//            get
//            {
//                return this.IdField;
//            }
//            set
//            {
//                this.IdField = value;
//            }
//        }
//    }
//}
namespace eCommerce.Services.WcfClient.Users
{
    using System.Runtime.Serialization;
    using eCommerce.Services.WcfClient.Common;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordKit", Namespace="http://schemas.datacontract.org/2004/07/eCommerce.Data.Domain.Users")]
    public partial class PasswordKit : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PasswordField;
        
        private StringFormatType PasswordFormatTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StringFormatType PasswordFormatType
        {
            get
            {
                return this.PasswordFormatTypeField;
            }
            set
            {
                this.PasswordFormatTypeField = value;
            }
        }
    }
}
namespace eCommerce.Services.WcfClient.Common
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringFormatType", Namespace="http://schemas.datacontract.org/2004/07/eCommerce.Data.Common")]
    public enum StringFormatType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClearText = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hashed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Encrypted = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserExtension")]
public interface IUserExtension
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserExtension/GetCharacteristicValue", ReplyAction="http://tempuri.org/IUserExtension/GetCharacteristicValueResponse")]
    string GetCharacteristicValue(long userId, string key);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserExtension/GetCharacteristicValue", ReplyAction="http://tempuri.org/IUserExtension/GetCharacteristicValueResponse")]
    System.Threading.Tasks.Task<string> GetCharacteristicValueAsync(long userId, string key);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserExtensionChannel : IUserExtension, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserExtensionClient : System.ServiceModel.ClientBase<IUserExtension>, IUserExtension
{
    
    public UserExtensionClient()
    {
    }
    
    public UserExtensionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserExtensionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserExtensionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserExtensionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetCharacteristicValue(long userId, string key)
    {
        return base.Channel.GetCharacteristicValue(userId, key);
    }
    
    public System.Threading.Tasks.Task<string> GetCharacteristicValueAsync(long userId, string key)
    {
        return base.Channel.GetCharacteristicValueAsync(userId, key);
    }
}
